### ISSUE TITLE
Having 2 services while only one should be created

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#25]
## Scenario
1- Run a blueprint to create one account and one vdc 
![errrror000](https://user-images.githubusercontent.com/15011431/36720660-5a3ea97a-1bb1-11e8-83ee-c4d254cba9de.png)

## Actual Result
- Under account folder: Two services have been created, one with the right data and the other with fake data.
- Same problem for other templates
![errrror](https://user-images.githubusercontent.com/15011431/36720665-5ed51316-1bb1-11e8-9494-6886c6cef54c.png)

**Comment by chrisvdg** [comment]
@john-kheir, not able to reproduce this, might have been fixed in the meantime.

**Comment by john-kheir** [comment]
Not there anymore
