### ISSUE TITLE
call install on a `node` that was already installed should not crash

### ISSUE THREAD

**Issue by muhamadazmy** [openvcloud/0-templates#34]
You either, do nothing, or raise an exception that it's already installed (state check)
currently it fails trying to create a filesystem on a mounted disk

**Comment by katia-e** [comment]
@muhamadazmy I've pushed on master check if machine already exists with commit https://github.com/openvcloud/0-templates/commit/1b07cf05778f38eb9cf40dc1d128806d0c8b58bc .

Should be fine, but I couldn't test it properly because I again have problems with environment.

**Comment by katia-e** [comment]
issue was fixed in previous commits
