### ISSUE TITLE
Create IYO service

### ISSUE THREAD

**Issue by katia-e** [openvcloud/0-templates#37]
- Create `iyo` service. The service checks whether instance `main` of `itsyou.online` exists. If `main` exists it creates `jwt` token, if doesn't exists - throws an error.
- `openvcloud` service:
  - make field `token` optional in blueprint
  - if `token` is not given, start `iyo` service to create `jwt` token.
  - remove `login` field from `openvcloud` template (still left in readme and `update` method)

**Comment by zaibon** [comment]
What would be the schema and actions of this IYO service ?

**Comment by katia-e** [comment]
@zaibon , 
``` capnp
struct Schema {
    # jwt token
    token @0 :Text; # filled in automatically
}
```
actions: ['get_jwt']

**Comment by katia-e** [comment]
No IYO template is currently needed.
