### ISSUE TITLE
Same account can't be created again on openvcloud.

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#44]
## Scenario
1- Run a blueprint to create account and cloud space.
2- Delete the account from the environment manually
3- Run the same blueprint again

## Actual Result
```
* Cloudspace still in deployment, will retry to create portforwarding in 2 second
^[[A^[[A^[[A^[[A^[[A^[[A* Get OpenvCloud client on URL: be-g8-3.demo.greenitglobe.com
* Get OpenvCloud client on URL: be-g8-3.demo.greenitglobe.com
[Sun11 09:20] - base.py           :210 :service-6d29bbf7-59eb-4c4e-a8c3-49cbc68a2287 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/root/0-robot/zerorobot/task/task.py", line 74, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/vdc/vdc.py", line 111, in install
    externalnetworkId=externalnetworkId
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Account.py", line 89, in space_get
    externalnetworkId=externalnetworkId)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 56, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 404 Not Found
Account does not exist
```

**Comment by chrisvdg** [comment]
Can't reproduce this @john-kheir . Can you test again with up to date code?

**Comment by john-kheir** [comment]
@chrisvdg Now I don't have this error .. but still the account can't be created again after rerunning the blueprint and that's my main concern here in this ticket.

**Comment by chrisvdg** [comment]
@john-kheir, s far as I'm aware deleting an account should not be done outside of 0-robot as that would complicate and add a lot of checks to the templates

**Comment by katia-e** [comment]
@john-kheir , 0-templates don't update changes done to account bypassing zrobot. We assume account and other ovc objects are managed by a single zrobot only. If the contrary happens, the templates are used wrong.

**Comment by john-kheir** [comment]
According to @zaibon and @grimpy  the current implementation is okay .. But that's assuming zero human interaction .
