### ISSUE TITLE
No check on the params provided in the blueprint.

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#47]
## Scenario
- Run a blueprint with wrong params

![bp](https://user-images.githubusercontent.com/15011431/37254391-af99da5a-2545-11e8-88d5-767b73ca5d8b.png)

## Actual results
- No user has been created because of the wrong "provide" or "emai".. No error from the terminal side (but there is an error in the server that no email is provided)
- Even if "provide" or "emai" was right and "user" (instead of users) is provided (which is wrong), Neither errors will be displayed in the server nor in the terminal side 

## Expected Result
There should be an error for any wrong param provided in the blueprint and it should be displayed in the terminal (not just the server)

**Comment by chrisvdg** [comment]
Current implementation indeed does not check if the provided service arguments are valid

@zaibon , @muhamadazmy Should we start checking them?

**Comment by zaibon** [comment]
yes you should. Have a look at other template to see how it's done: 
- https://github.com/zero-os/0-templates/blob/master/templates/node/node.py#L28
- https://github.com/openvcloud/0-templates/blob/master/templates/node/node.py#L25
- https://github.com/Jumpscale/0-robot/tree/master/docs/services#validate-service-data-received-during-creation

**Comment by chrisvdg** [comment]
Most of the templates do implement the validate method but only check for required fields in the data.
Will add checks if provided service arguments are supported.

**Comment by katia-e** [comment]
Closed for the same reason as https://github.com/zero-os/0-templates/issues/78
Wrongly spelled parameters will be ignored, `validate` in all templates checks that required parameters are given.
