### ISSUE TITLE
Services not present when executing a blueprint should not get deleted because they are not in the blueprint

### ISSUE THREAD

**Issue by FastGeert** [openvcloud/0-templates#51]
This behaviour was copied from the AYS templates, but is actually wrong.

**Comment by zaibon** [comment]
for more context.
This issue concern the current behavior of the vdc template for example.
Current way of working is when a blueprint is sent, with a list of vdc user, this list of user is applied to the vdc. which means, if you have a vdc where 10 user are authorized, but then you send a blueprint where you don't list all the user, these not listed user will unauthorized. This behavior is quite dangerous and make blueprint super hard to write.

My idea to deal with that is. we don't let the user beeing listed in the blueprint. Instead when the services installs, we load its data from the really.
Then if we want to authorize and unauthorize user, we use actions.

**Comment by katia-e** [comment]
@FastGeert , @zaibon , Do we need to store `accesstype` of the users in schema?
In case we load current list of users from space: `space.authorized_users` returns only usernames. We will know access right only if we add user or change access rights.
