### ISSUE TITLE
sshkey template should validate the data inside the self.validate() method

### ISSUE THREAD

**Issue by zaibon** [openvcloud/0-templates#61]
See the documentation about validate() method: https://github.com/Jumpscale/0-robot/tree/master/docs/services#validate-service-data-received-during-creation

**Comment by chrisvdg** [comment]
All the logic is in the constructor, but validation is run after that has been called and the key should be loaded already so `dir` and `passphrase` aren't actually really needed anymore.
So either the logic needs to move to install or validate should check if the key has been loaded or something?

**Comment by katia-e** [comment]
@zaibon , currently all logic of `sshkey` service is creating key and loading in to the ssh-agent. We run no actions on it, and we user it only for node template. Why don't we move it all to the node template then?
